# Generated by Django 5.1.7 on 2025-04-15 00:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='curtidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postagem',
            name='descurtidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data_postagem',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
