# Generated by Django 5.1.7 on 2025-04-15 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_postagem_curtidas_postagem_descurtidas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='curtidas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data_postagem',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='descurtidas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='postagens/'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='nome_usuario',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='socialapp.postagem')),
            ],
        ),
    ]
